// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1677501040);
user_pref("browser.search.region", "KR");
user_pref("calendar.list.sortOrder", "d8227f1a-3e67-4399-97a7-aa078c186ff4");
user_pref("calendar.registry.d8227f1a-3e67-4399-97a7-aa078c186ff4.calendar-main-default", true);
user_pref("calendar.registry.d8227f1a-3e67-4399-97a7-aa078c186ff4.calendar-main-in-composite", true);
user_pref("calendar.registry.d8227f1a-3e67-4399-97a7-aa078c186ff4.disabled", true);
user_pref("calendar.registry.d8227f1a-3e67-4399-97a7-aa078c186ff4.name", "Home");
user_pref("calendar.registry.d8227f1a-3e67-4399-97a7-aa078c186ff4.type", "storage");
user_pref("calendar.registry.d8227f1a-3e67-4399-97a7-aa078c186ff4.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Seoul");
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1677501039);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20221101185644");
user_pref("extensions.lastAppVersion", "102.4.2");
user_pref("extensions.lastPlatformVersion", "102.4.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"c1227ee6-cbb3-4f93-ab76-3aa1d1e20378\",\"google@search.mozilla.org\":\"df95a2c3-551e-43e1-8cb4-39e6e2b1bd28\",\"ddg@search.mozilla.org\":\"f85a2896-71f3-4a15-b5eb-df595412eb6a\",\"amazondotcom@search.mozilla.org\":\"25d73332-a247-4653-8870-5715aaa1bb3e\",\"wikipedia@search.mozilla.org\":\"e69bdc9b-abdc-40c3-bc16-592db648226d\",\"bing@search.mozilla.org\":\"8f1f0535-e900-49b7-80fe-32e1e0385ca4\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 34);
user_pref("mailnews.database.global.datastore.id", "3beb37eb-1635-42e8-ab4d-7dec25a809c");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "102.4.2");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.cachedClientID", "687ef1f6-1ba5-4f22-9a2f-308c0cbb6efc");
user_pref("toolkit.telemetry.previousBuildID", "20221101185644");
